// ignore_for_file: constant_identifier_names
enum FunctionCode {
  FULL_TERMINAL_CONFIGURATION,
  PARTIAL_TERMINAL_CONFIGURATION,
  FORCE_RECONCILIATION,
  NORMAL_RECONCILIATION,
  REVERSE_TRANSACTION,
  CANCEL_TRANSACTION;
}
