import requests
import uuid

BASE_URL = "http://localhost:8080"
LOGIN_URL = f"{BASE_URL}/api/auth/login"
HELD_CARTS_URL = f"{BASE_URL}/api/pos/held-carts"
TIMEOUT = 30

email = "owner@ostora.sa"
password = "owner@ostora.sa"

def test_pos_held_carts_api():
    # Authenticate and get Bearer token
    try:
        login_resp = requests.post(
            LOGIN_URL,
            json={"email": email, "password": password},
            timeout=TIMEOUT,
        )
        assert login_resp.status_code == 200, f"Login failed: {login_resp.text}"
        token = login_resp.json().get("token")
        assert token, "No token in login response"
        headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

        # Create a held cart via POST /api/pos/held-carts
        # Construct a sample cart payload with minimal required details (ID autogenerated)
        cart_payload = {
            "name": f"Test Cart {uuid.uuid4()}",
            "items": [
                {
                    "product_id": 1,
                    "quantity": 2,
                    "price": 10.0
                }
            ],
            "notes": "Test cart created by automated test"
        }

        post_resp = requests.post(HELD_CARTS_URL, json=cart_payload, headers=headers, timeout=TIMEOUT)
        assert post_resp.status_code == 201, f"Failed to create held cart: {post_resp.text}"
        created_cart = post_resp.json()
        cart_id = created_cart.get("id")
        assert cart_id, "Created cart has no id"

        # Retrieve held carts list via GET /api/pos/held-carts
        get_resp = requests.get(HELD_CARTS_URL, headers=headers, timeout=TIMEOUT)
        assert get_resp.status_code == 200, f"Failed to list held carts: {get_resp.text}"
        carts_list = get_resp.json()
        assert isinstance(carts_list, list), "Held carts list response not a list"

        # Verify the created cart is in the list by id
        matching = [cart for cart in carts_list if cart.get("id") == cart_id]
        assert len(matching) == 1, "Created held cart not found in list"

    finally:
        # Clean up: delete the created held cart
        if 'cart_id' in locals():
            del_resp = requests.delete(f"{HELD_CARTS_URL}/{cart_id}", headers=headers, timeout=TIMEOUT)
            assert del_resp.status_code in (200, 204), f"Failed to delete held cart: {del_resp.text}"

test_pos_held_carts_api()