// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV6E0Yar1EadbwsnKZdvCDSdfr8wuC29U',
    appId: '1:175672507424:web:9e04836a746e173b971045',
    messagingSenderId: '175672507424',
    projectId: 'wameedpos',
    authDomain: 'wameedpos.firebaseapp.com',
    storageBucket: 'wameedpos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSLDiHJ8X0zsvomD5RPLWhdjdWALSLtPQ',
    appId: '1:175672507424:android:33a32a3e0386f9a4971045',
    messagingSenderId: '175672507424',
    projectId: 'wameedpos',
    storageBucket: 'wameedpos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXFVHj_SSFFvTyd_6ssrIi2IvwmITBbBw',
    appId: '1:175672507424:ios:49577ea3dae61eff971045',
    messagingSenderId: '175672507424',
    projectId: 'wameedpos',
    storageBucket: 'wameedpos.firebasestorage.app',
    iosBundleId: 'com.wameedpos.provider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXFVHj_SSFFvTyd_6ssrIi2IvwmITBbBw',
    appId: '1:175672507424:ios:49577ea3dae61eff971045',
    messagingSenderId: '175672507424',
    projectId: 'wameedpos',
    storageBucket: 'wameedpos.firebasestorage.app',
    iosBundleId: 'com.wameedpos.provider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV6E0Yar1EadbwsnKZdvCDSdfr8wuC29U',
    appId: '1:175672507424:web:325efff916c22ec5971045',
    messagingSenderId: '175672507424',
    projectId: 'wameedpos',
    authDomain: 'wameedpos.firebaseapp.com',
    storageBucket: 'wameedpos.firebasestorage.app',
  );
}
